title: Hailey's Draft Website
author: Hailey Mortimore (Hmortimore)
email: hmortimore@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Hailey Mortimore's personal and professional website. You can find my resume, contact, and learn a little bit more about me here. This site is under construction

# social links
github_username:  hmortimore

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
